export const portfolioData = {
  profile: {
    name: "김수현",
    eyebrow: "B2B AI · DATA SERVICES",
    title: "AI와 데이터 기술을\n실제 서비스로\n구현합니다",
    summary:
      "Text-to-SQL과 LLM 연동부터 데이터 처리, 인증, 배포까지 AI 서비스의 백엔드와 운영 환경을 구현해 왔습니다. C#/.NET 백엔드와 TypeScript/React 프론트엔드를 함께 다룹니다.",
    asOf: "자료 기준일 2026.08",
  },
  capabilities: [
    {
      index: "01",
      title: "AI 서비스",
      detail: "Text-to-SQL DAG, Azure OpenAI, LLM SDK 마이그레이션",
      proof: "자연어 질의를 실행 가능한 단계로 나누고, 실패와 재시도를 추적합니다.",
    },
    {
      index: "02",
      title: "데이터 처리",
      detail: "입력 검증, 정규화, 시계열 집계, 문서·Excel 파싱",
      proof: "입력부터 저장까지 일관된 기준을 적용해 결과를 신뢰할 수 있게 합니다.",
    },
    {
      index: "03",
      title: "제품 운영",
      detail: "인증 세션, API 재시도, 런타임 설정, 배포 자동화",
      proof: "인증과 오류 대응, 환경 설정까지 서비스가 운영되는 조건을 함께 구현합니다.",
    },
  ],
  cases: [
    {
      number: "01",
      label: "AI 질의 백엔드",
      period: "2026.07",
      project: "AI 질의 플랫폼",
      role: "백엔드·오케스트레이션",
      scope: "Text-to-SQL · DAG · SQL 검증",
      title: "Text-to-SQL 실행 흐름 설계",
      summary:
        "자연어 질의를 계획, SQL 생성, 검증, 응답 단계로 나누고 실패와 재시도를 추적할 수 있는 DAG 실행 흐름을 구성했습니다.",
      problem:
        "여러 단계의 판단과 데이터 조회가 한 흐름에 묶여 있어 실패 원인과 재시도 지점을 찾기 어려웠습니다.",
      contributions: [
        "Text-to-SQL 처리 단계를 DAG 노드로 분리하고 병렬 실행과 fan-in 구성",
        "노드별 결과·실패·토큰 사용량을 실행 context에 기록",
        "SELECT-only 검사와 날짜 조건 guard로 SQL 실행 전 안전 조건 확인",
        "PostgreSQL timeout·deadlock·serialization 오류를 분류해 재시도 적용",
      ],
      stack: ["C#/.NET", "Text-to-SQL", "DAG orchestration", "Azure", "SQL"],
      decisions: [
        "각 처리 결과를 다음 노드의 명시적인 입력으로 전달",
        "클라우드 자격 증명과 런타임 설정을 애플리케이션 코드와 분리",
        "SQL 생성과 실행 사이에 검증 단계를 두어 위험한 쿼리를 차단",
      ],
      outcome: "질의 처리 단계별 결과와 실패 원인을 추적하고 SQL 안전 조건을 회귀 테스트로 확인할 수 있게 했습니다.",
      evidence: "코드 감사: 오케스트레이션 서비스·DAG 실행 엔진·SQL 노드의 DAG, fan-in, SELECT guard 경계를 확인",
    },
    {
      number: "02",
      label: "금융 AI 백엔드",
      period: "2026.06",
      project: "금융 AI 서비스",
      role: "AI 백엔드·SDK 마이그레이션",
      scope: "Azure OpenAI · 입력·출력 검증 · 토큰 집계",
      title: "LLM 연동과 응답 검증 안정화",
      summary: "34개 TCB 모듈의 입력·출력 검증, 재시도, 토큰 집계를 하나의 처리 흐름으로 정리했습니다.",
      problem: "SDK와 설정이 바뀔 때마다 모델 호출, 토큰 사용량, 오류 응답을 함께 수정해야 했습니다.",
      contributions: ["필수 입력 필드를 모델 호출 전에 검증하고 프롬프트별 출력 규칙 적용", "Azure OpenAI 호출과 streaming 응답의 token usage 집계", "usage가 없는 응답에 토큰 계산 fallback 적용", "provider 오류에서 내부 정보를 제거하고 사용자용 한국어 응답으로 변환"],
      stack: ["C#/.NET", "Azure OpenAI", "SDK v2", "환경변수 구성"],
      decisions: ["모델 호출, 환경 설정, 응답 검증의 책임 분리", "검증 실패에 최대 5회 재시도 적용", "토큰 사용량과 오류 응답을 테스트 가능한 계약으로 고정"],
      outcome: "모델과 SDK가 바뀌어도 입력 검증, 사용량 집계, 오류 처리를 독립적으로 수정할 수 있게 했습니다.",
      evidence: "코드 감사: TCB 처리·Azure chat client의 typed module, retry, token usage 경계를 확인",
    },
    {
      number: "03",
      label: "인증·실행 플랫폼 runtime",
      period: "2026.03",
      project: "인증·실행 플랫폼 · runtime",
      role: "프론트엔드 빌드·런타임·인증",
      scope: "Next.js standalone · 런타임 설정 · 인증 쿠키",
      title: "환경별로 재사용하는 Next.js 배포",
      summary: "Next.js standalone 빌드와 런타임 환경 설정을 분리해 같은 산출물을 여러 배포 환경에서 사용할 수 있게 했습니다.",
      problem: "API 주소가 빌드 시점에 고정되고 인증 쿠키 정책이 환경마다 달라 배포할 때마다 새 빌드와 수정이 필요했습니다.",
      contributions: ["Next.js standalone 산출물과 /api runtime rewrite 분리", "런타임 환경변수로 API 연결 설정 주입", "refresh token 쿠키의 브라우저·배포 조건 점검", "실행 절차를 자동화 스크립트와 가이드로 정리"],
      stack: ["TypeScript", "Next runtime", "standalone build", "refresh token", "Chrome DevTools"],
      decisions: ["환경별 설정을 빌드 산출물 밖에서 주입", "인증 쿠키 동작을 배포 조건과 함께 검증", "반복되는 실행 절차를 스크립트로 고정"],
      outcome: "새로 빌드하지 않고도 환경별 API 설정을 적용하고 동일한 실행 절차를 재현할 수 있게 했습니다.",
      evidence: "코드 감사: auth/token route·axios interceptor·standalone Next config의 실행 경계를 확인",
    },
    {
      number: "04",
      label: "인증·실행 플랫폼 web",
      period: "2026.03",
      project: "인증·실행 플랫폼 · web",
      role: "인증 세션·모델 관리 UI",
      scope: "HttpOnly cookie · OAuth · 모델 관리",
      title: "인증부터 모델 선택까지 이어지는 제품 흐름",
      summary: "HttpOnly cookie 기반 인증과 모델·프로바이더 관리 화면을 연결해 로그인부터 채팅 모델 선택까지 하나의 흐름으로 구현했습니다.",
      problem: "인증 상태와 모델 설정이 서로 다른 레이어에 나뉘어 사용자가 현재 상태를 확인하고 문제를 복구하기 어려웠습니다.",
      contributions: ["provider token을 브라우저 JSON에 노출하지 않고 HttpOnly cookie로 발급", "동시에 발생한 refresh 요청을 하나로 합치고 실패한 원 요청을 한 번만 재시도", "모델·프로바이더 설정과 채팅 모델 선택 UI 구현", "문서 삭제·이동 요청에 Idempotency-Key 적용"],
      stack: ["TypeScript/React", "HttpOnly cookie", "OAuth", "Cosmos DB", "standalone"],
      decisions: ["브라우저 인증 상태를 token route에서 일관되게 관리", "모델 설정을 화면에서 확인·수정 가능한 상태로 제공", "중복될 수 있는 변경 요청에 idempotency 적용"],
      outcome: "로그인, 세션 갱신, 모델 설정, 채팅 선택이 끊기지 않는 사용자 흐름을 만들었습니다.",
      evidence: "코드 감사: auth/token route·api-client의 동시 refresh·401 retry와 문서 삭제·이동 Idempotency-Key를 확인",
    },
    {
      number: "05",
      label: "인증·실행 플랫폼 backend",
      period: "2025.06",
      project: "인증·실행 플랫폼 · backend",
      role: "Keycloak·Identity 모듈",
      scope: "Keycloak · ASP.NET Identity · REST API",
      title: "Keycloak·Identity 인증 흐름 정비",
      summary: "Keycloak 로그인과 ASP.NET Identity 모듈의 역할을 나누고 인증 흐름을 일관된 API 계약으로 정리했습니다.",
      problem: "로그인과 사용자 도메인 로직의 책임이 섞여 인증 변경이 다른 기능에 미치는 영향을 예측하기 어려웠습니다.",
      contributions: ["authorization code·password·refresh token 흐름 구현", "로그인과 사용자 Identity 모듈의 책임 분리", "인증 실패를 RFC ProblemDetails 형식으로 반환", "EF 기반 모델 목록 조회와 paging 구현"],
      stack: ["C#/.NET", "Keycloak", "Identity", "REST API"],
      decisions: ["인증 제공자 연동과 사용자 도메인 로직 분리", "인증 상태를 백엔드에서 검증", "오류 응답 형식을 API 전반에서 통일"],
      outcome: "인증 제공자나 로그인 방식이 바뀌어도 사용자 도메인 기능과 오류 응답을 독립적으로 관리할 수 있게 했습니다.",
      evidence: "코드 감사: KeyCloakService의 authorization/password/refresh 흐름과 EF 기반 model paging을 확인",
    },
    {
      number: "06",
      label: "온프레미스 AI 에이전트",
      period: "2025.12",
      project: "온프레미스 AI 에이전트",
      role: "에이전트 오케스트레이션·운영 UI",
      scope: "Agent handoff · SignalR · MongoDB",
      title: "멀티 에이전트 handoff와 실시간 운영",
      summary: "여러 에이전트가 작업을 넘겨받는 과정과 응답 상태를 운영자가 실시간으로 확인할 수 있게 구현했습니다.",
      problem: "에이전트가 어떤 판단으로 다음 역할을 선택했고 응답이 어디까지 진행됐는지 한 화면에서 확인하기 어려웠습니다.",
      contributions: ["Email·Jira·Meeting agent를 function tool로 연결", "triage에서 전문 agent로 이어지는 handoff workflow 구성", "SignalR로 응답 chunk와 완료 이벤트 전달", "대화 thread를 MongoDB에 저장하고 저장 실패 fallback 적용"],
      stack: ["AI agents", "orchestration workflow", "on-premise", "3-panel dashboard", "i18n"],
      decisions: ["agent 전환을 명시적인 workflow 단계로 표현", "streaming 중간 상태와 완료 상태를 별도 이벤트로 전달", "세션과 응답 언어를 handoff 이후에도 유지"],
      outcome: "운영자가 agent 전환, 실시간 응답, 대화 이력을 한 흐름에서 확인할 수 있게 했습니다.",
      evidence: "코드 감사: 오케스트레이터·handoff workflow·채팅 허브의 SignalR streaming과 Mongo thread 저장을 확인",
    },
    {
      number: "08",
      label: "금융 문서 PoC",
      period: "2025.08",
      project: "금융 문서 PoC",
      role: "PoC 기능·검증 결과 UI",
      scope: "Excel 검증 · 결과 계약 · Azure Functions",
      title: "문서 검증 결과를 다음 행동으로 연결",
      summary: "Excel 문서의 검증 결과와 오류 항목을 사용자가 원인과 수정 방향을 이해할 수 있는 형태로 제공했습니다.",
      problem: "검증 실패가 단순 오류 문자열로만 표시되어 어떤 행을 어떻게 수정해야 하는지 판단하기 어려웠습니다.",
      contributions: ["Excel sheet·converter·validation class를 동적으로 로드", "상태·행 수·오류 수·diff를 ValidationResult로 통합", "검증 결과를 CSV·XLSX로 저장하고 오류 CSV 재분석 지원", "Azure Function 호출에 단계별 오류 응답과 timeout 적용"],
      stack: ["C#/.NET", "document processing", "PoC", "validation UI"],
      decisions: ["오류 상태와 결과 파일 정보를 하나의 응답 계약으로 제공", "검증 조건과 실패 항목을 함께 표시", "후속 분석이 같은 오류 데이터를 다시 사용할 수 있게 구성"],
      outcome: "사용자가 검증 실패 지점과 수정 대상을 확인하고 같은 데이터로 후속 분석을 이어갈 수 있게 했습니다.",
      evidence: "코드 감사: 분석 서비스·ValidationResult와 후속 오류 CSV 재분석, Azure Function 경계를 확인",
    },
    {
      number: "09",
      label: "인증 프론트엔드",
      period: "2025.03",
      project: "React 인증 예제",
      role: "React·Keycloak 인증 프론트엔드",
      scope: "React · Keycloak · 인증 UI",
      title: "React·Keycloak 인증 화면",
      summary: "React와 Keycloak을 연동한 인증 프론트엔드 개발을 담당했습니다.",
      problem: "로그인 상태와 접근 권한을 화면에서 일관되게 처리하는 기능이 필요했습니다.",
      contributions: ["React 기반 인증 화면 개발", "Keycloak 로그인 연동"],
      stack: ["React", "Keycloak", "Authentication"],
      decisions: ["세부 설계 판단은 공개 코드가 없어 기재하지 않았습니다."],
      outcome: "React·Keycloak 인증 프론트엔드 개발 경험을 쌓았습니다.",
      evidence: "이번 clone 감사 범위 외 저장소로, 공개 이력서의 코드 근거에는 포함하지 않음",
    },
    {
      number: "10",
      label: "문서 파싱 서비스",
      period: "2025.03",
      project: "문서 파싱 API",
      role: "서비스 초기 구조·안정화",
      scope: "API · 문서 파싱 · 오류 대응",
      title: "문서 파싱 API 초기 구조와 안정화",
      summary: "문서 파싱 서비스의 초기 API 구조를 만들고 오류를 수정하며 서비스 흐름을 안정화했습니다.",
      problem: "다양한 문서 입력을 일관된 API 형식으로 처리하고 실패 상황에 대응할 초기 구조가 필요했습니다.",
      contributions: ["문서 파싱 API 초기 구조 개발", "서비스 오류 수정과 안정화"],
      stack: ["API", "Document parsing"],
      decisions: ["세부 설계 판단은 공개 코드가 없어 기재하지 않았습니다."],
      outcome: "문서 파싱 기능을 서비스에서 사용할 수 있는 API 형태로 구현했습니다.",
      evidence: "이번 clone 감사 범위 외 저장소로, 공개 이력서의 코드 근거에는 포함하지 않음",
    },
    {
      number: "11",
      label: "진단 업무 시스템",
      period: "2024.12",
      project: "진단 rulebase",
      role: "검사 업무 로직·오류 수정",
      scope: "Excel rulebase · 계층 검증 · 카드 UI",
      title: "Excel rulebase 검증과 화면 흐름 개선",
      summary: "Excel로 관리되는 검사 규칙을 안전하게 불러오고 질문·답변 단계와 이전 단계 이동을 화면에 연결했습니다.",
      problem: "병합 셀과 계층형 규칙의 오류가 그대로 저장되면 검사 단계가 잘못 연결되고 사용자가 이전 선택으로 돌아가기 어려웠습니다.",
      contributions: ["단일 sheet·필수 header·병합 셀 계층 검증", "sanitize 과정에서 값이 바뀐 행을 행 번호와 함께 거부", "질문·답변 계층을 저장 모델로 변환", "카드 UI에 다음 단계와 go-back 흐름 구현"],
      stack: ["C#/.NET", "diagnostics", "business rules", "SQL"],
      decisions: ["잘못된 규칙을 보정해 저장하지 않고 입력 단계에서 명확히 거부", "질문 계층과 화면 이동 규칙을 같은 모델로 관리", "이전 선택으로 돌아가도 다음 단계가 일관되게 계산되도록 구성"],
      outcome: "잘못된 rulebase 입력을 저장 전에 차단하고 사용자가 검사 단계를 앞뒤로 이동할 수 있게 했습니다.",
      evidence: "코드 감사: Excel ingestion의 rulebase 계층 검증·sanitize와 카드 UI의 go-back 흐름을 확인",
    },
    {
      number: "12",
      label: "AI 상담 모니터링",
      period: "2024.06",
      project: "AI 상담·모니터링 서비스",
      role: "풀스택 대시보드·조회 기능",
      scope: "AI 상담 · 모니터링 · 데이터 조회",
      title: "AI 상담 운영 대시보드",
      summary: "AI 상담 상태와 관련 데이터를 조회하는 운영 대시보드의 풀스택 기능을 개발했습니다.",
      problem: "상담 진행 상태와 운영 데이터를 한곳에서 확인할 수 있는 화면이 필요했습니다.",
      contributions: ["상담 운영 대시보드 개발", "운영 데이터 조회 기능 구현"],
      stack: ["Full-stack", "Dashboard", "Data query"],
      decisions: ["세부 설계 판단은 공개 코드가 없어 기재하지 않았습니다."],
      outcome: "AI 상담 운영 정보를 조회할 수 있는 화면을 구현했습니다.",
      evidence: "이번 clone 감사 범위 외 저장소로, 공개 이력서의 코드 근거에는 포함하지 않음",
    },
    {
      number: "13",
      label: "구독·청구 시스템",
      period: "2023.10",
      project: "구독 청구",
      role: "청구·구독 업무 기능",
      scope: "CSV 집계 · 재처리 · Cosmos DB",
      title: "구독 청구 데이터 집계와 복구 흐름",
      summary: "청구 CSV를 구독 단위로 집계하고 누락 정보를 보완한 뒤 Cosmos DB에 저장하는 처리 흐름을 구현했습니다.",
      problem: "주문 라인이 파일마다 나뉘고 reseller 정보가 비어 있어 구독별 청구 금액과 분류를 일관되게 계산하기 어려웠습니다.",
      contributions: ["subscriptionId별 주문 라인의 subtotal·tax·total 합산", "누락된 reseller 식별자를 과거 레코드에서 보완", "기간별 데이터를 제거한 뒤 다시 처리하는 reset 경로 구현", "Cosmos DB bulk write와 파일 단위 오류 격리"],
      stack: ["C#/.NET", "subscription", "billing", "SQL"],
      decisions: ["청구 데이터를 파일이 아닌 구독 식별자 기준으로 집계", "누락 분류는 확인 가능한 과거 데이터로만 보완", "한 파일의 실패가 전체 처리를 중단하지 않도록 격리"],
      outcome: "구독별 청구 금액과 분류 정보를 일관되게 계산하고 문제가 있는 파일만 분리해 재처리할 수 있게 했습니다.",
      evidence: "코드 감사: 청구 서비스의 subscriptionId 그룹화·reseller 보완과 Cosmos bulk write 경계를 확인",
    },
    {
      number: "14",
      label: "건강 데이터 백엔드",
      period: "2023.09",
      project: "건강 데이터",
      role: "데이터 정규화·통계 기능",
      scope: "증분 조회 · 단위 변환 · 기간 통계",
      title: "건강 데이터 증분 집계와 단위 표준화",
      summary: "변경된 건강 데이터만 읽어 단위를 통일하고 일·주·월·연 단위 통계로 제공하는 백엔드를 구현했습니다.",
      problem: "데이터 소스마다 혈당 단위와 갱신 시점이 달라 같은 기간의 통계 결과를 일관되게 계산하기 어려웠습니다.",
      contributions: ["MongoDB 변경 시점과 Cosmos DB checkpoint를 비교해 변경분만 조회", "mmol/L 값을 mg/dL로 변환해 저장 단위 통일", "source·date별 전체·공복·식후 통계를 bulk upsert", "기간 조회에서 사전 집계 데이터를 평균·최소·최대로 재구성"],
      stack: ["C#/.NET", "Cosmos DB", "health data", "statistics"],
      decisions: ["마지막 처리 시점 이후의 변경분만 집계", "저장 전에 단위를 하나로 통일", "조회 시점의 반복 계산을 줄이기 위해 기간별 기초 통계를 미리 저장"],
      outcome: "변경된 데이터만 다시 계산하면서도 서로 다른 소스의 혈당 값을 같은 기준으로 비교할 수 있게 했습니다.",
      evidence: "코드 감사: Mongo checkpoint 증분 조회·단위 정규화·Cosmos glucose 통계 upsert 경계를 확인",
    },
    {
      number: "15",
      label: "주문·업로드 시스템",
      period: "2023.08",
      project: "주문 업로드 서비스",
      role: "업로드 양식·변환 오류 개선",
      scope: "주문 업로드 · 데이터 변환 · 오류 수정",
      title: "주문 업로드와 데이터 변환 개선",
      summary: "주문 업로드 양식과 데이터 변환 과정에서 발생하는 오류를 수정했습니다.",
      problem: "업로드 형식과 변환 규칙이 맞지 않을 때 주문 데이터가 정상적으로 처리되지 않았습니다.",
      contributions: ["주문 업로드 양식 개선", "데이터 변환 오류 수정"],
      stack: ["File upload", "Data transformation"],
      decisions: ["세부 설계 판단은 공개 코드가 없어 기재하지 않았습니다."],
      outcome: "주문 파일을 업무 데이터로 변환하는 업로드 기능을 개선했습니다.",
      evidence: "이번 clone 감사 범위 외 저장소로, 공개 이력서의 코드 근거에는 포함하지 않음",
    },
    {
      number: "16",
      label: "문서·지식 AI",
      period: "2023.08",
      project: "문서 지식 기반 AI",
      role: "KnowledgeBase·문서 인식 연동",
      scope: "KnowledgeBase · 문서 인식 · AI 연동",
      title: "문서 인식과 KnowledgeBase 연동",
      summary: "문서 인식 결과를 KnowledgeBase에서 활용할 수 있도록 AI 서비스 연동 기능을 개발했습니다.",
      problem: "문서에서 추출한 정보를 지식 기반 AI 기능으로 전달하는 연결 과정이 필요했습니다.",
      contributions: ["문서 인식 서비스 연동", "KnowledgeBase 기능 연결"],
      stack: ["Document AI", "KnowledgeBase"],
      decisions: ["세부 설계 판단은 공개 코드가 없어 기재하지 않았습니다."],
      outcome: "문서 정보를 지식 기반 AI 기능에서 활용하는 연동 경험을 쌓았습니다.",
      evidence: "이번 clone 감사 범위 외 저장소로, 공개 이력서의 코드 근거에는 포함하지 않음",
    },
    {
      number: "17",
      label: "제조 리포트 웹앱",
      period: "2023.07",
      project: "제조 품질 리포트",
      role: "리포트 웹 애플리케이션",
      scope: "CPVR·APQR · LIMS · 차트·다운로드",
      title: "제조 품질 리포트 구현",
      summary: "제조 품질 데이터를 그룹화해 차트와 표로 보여주고 필터, 다운로드, 인쇄까지 이어지는 리포트 웹앱을 개발했습니다.",
      problem: "조회 결과의 상태와 LIMS 매핑이 복잡하고 현장에서는 같은 데이터를 화면, Excel, 인쇄물로 확인해야 했습니다.",
      contributions: ["리포트 데이터를 식별자 기준으로 그룹화하고 partial·full 상태 표시", "LIMS parameter 매핑과 spec·decimal 표시 처리", "차트·trend·table 분기와 필터 기능 구현", "Excel 다운로드와 인쇄 흐름, 오류 모달 구현"],
      stack: ["TypeScript", "React", "Power BI", "LIMS", "SQL"],
      decisions: ["화면과 다운로드가 같은 데이터 변환 결과를 사용하도록 구성", "partial·full 상태와 빈 값을 화면에 명확히 표시", "표·차트·인쇄를 사용 목적에 맞게 분리"],
      outcome: "제조 품질 데이터를 한 화면에서 조회·비교하고 Excel과 인쇄물로 이어서 사용할 수 있게 했습니다.",
      evidence: "코드 감사: 리포트 테이블의 그룹화·partial/full 표시와 LIMS mapping·차트·다운로드 경계를 확인",
    },
    {
      number: "18",
      label: "제조 서버리스 로직",
      period: "2023.04",
      project: "제조 서버리스 로직",
      role: "업무 로직·서버리스 백엔드",
      scope: "Azure Functions · LIMS · 제조 계산",
      title: "제조 계산 로직의 서버리스 분리",
      summary: "LIMS 매핑과 제조 지표 계산을 Azure Functions로 분리해 리포트에서 재사용할 수 있는 백엔드 기능으로 만들었습니다.",
      problem: "리포트 화면이 제조 계산 규칙까지 직접 처리해 계산 변경과 데이터 이력을 관리하기 어려웠습니다.",
      contributions: ["LIMS mapping 조회·수정 기능 구현", "report flag와 원천 데이터 상태에 따른 처리 분기", "제조 order와 inspection lot를 batch 기준으로 결합", "Blob Excel 조건을 계산해 Initial·Final 결과 생성"],
      stack: ["C#/.NET", "Azure Functions", "LIMS", "calculation"],
      decisions: ["업무 계산을 화면에서 Azure Functions로 이동", "매핑 관리와 계산 실행의 책임 분리", "제조 order의 취소 시점을 계산 조건에 반영"],
      outcome: "제조 리포트가 공통 계산 결과를 사용하고 업무 규칙을 백엔드에서 독립적으로 변경할 수 있게 했습니다.",
      evidence: "코드 감사: LIMS mapping·MSP/EBR 계산 Azure Function과 CSV 산출 경계를 확인",
    },
    {
      number: "19",
      label: "ASP.NET 인증 예제",
      period: "2023.02",
      project: "Identity 예제",
      role: "ASP.NET Identity 초기 구조",
      scope: "ASP.NET · Identity · 인증",
      title: "ASP.NET Identity 인증 구조",
      summary: "ASP.NET Identity를 사용하는 인증 기능의 초기 구조를 구현했습니다.",
      problem: "사용자 계정과 인증 상태를 관리할 기본 구조가 필요했습니다.",
      contributions: ["ASP.NET Identity 기반 인증 구조 개발"],
      stack: ["ASP.NET", "Identity", "Authentication"],
      decisions: ["세부 설계 판단은 공개 코드가 없어 기재하지 않았습니다."],
      outcome: "ASP.NET Identity 기반 사용자 인증 개발 경험을 쌓았습니다.",
      evidence: "이번 clone 감사 범위 외 저장소로, 공개 이력서의 코드 근거에는 포함하지 않음",
    },
    {
      number: "20",
      label: "금융 PoC 채팅 UI",
      period: "2022.12",
      project: "금융권 AI PoC",
      role: "채팅 UX·피드백 기능",
      scope: "AI 채팅 · 사용자 피드백 · PoC",
      title: "금융 AI PoC 채팅 경험",
      summary: "금융권 AI PoC에서 채팅 화면과 응답 피드백 기능을 개발했습니다.",
      problem: "사용자가 AI 응답을 확인하고 결과에 대한 피드백을 남길 화면이 필요했습니다.",
      contributions: ["AI 채팅 화면 개발", "응답 피드백 기능 구현"],
      stack: ["AI chat", "Feedback UI", "PoC"],
      decisions: ["세부 설계 판단은 공개 코드가 없어 기재하지 않았습니다."],
      outcome: "AI 응답과 사용자 피드백을 연결하는 채팅 UI를 구현했습니다.",
      evidence: "이번 clone 감사 범위 외 저장소로, 공개 이력서의 코드 근거에는 포함하지 않음",
    },
    {
      number: "21",
      label: "인증·실행 플랫폼 공통 도메인",
      period: "2022.11",
      project: "인증·실행 플랫폼 공통 모델",
      role: "도메인 모델·고객 기능",
      scope: "공통 모델 · 도메인 기능 · API",
      title: "업무 기능을 위한 공통 도메인 모델",
      summary: "인증·실행 플랫폼의 여러 업무 기능에서 함께 사용하는 도메인 모델과 고객 기능을 개발했습니다.",
      problem: "업무 기능마다 같은 개념을 다르게 다루지 않도록 공통 모델이 필요했습니다.",
      contributions: ["공통 도메인 모델 개발", "고객 업무 기능 구현"],
      stack: ["Domain model", "API"],
      decisions: ["세부 설계 판단은 공개 코드가 없어 기재하지 않았습니다."],
      outcome: "여러 업무 기능에서 사용하는 공통 모델 개발을 담당했습니다.",
      evidence: "이번 clone 감사 범위 외 저장소로, 공개 이력서의 코드 근거에는 포함하지 않음",
    },
    {
      number: "22",
      label: "인증·실행 플랫폼 업무 애플리케이션",
      period: "2021.12",
      project: "인증·실행 플랫폼 업무 기능",
      role: "Guide·Reference 업무 기능",
      scope: "Guide · Reference · 업무 애플리케이션",
      title: "Guide·Reference 업무 기능",
      summary: "인증·실행 플랫폼에서 지식 정보를 조회하고 활용하는 Guide·Reference 업무 기능을 개발했습니다.",
      problem: "업무에 필요한 안내와 참고 정보를 제품 안에서 제공할 기능이 필요했습니다.",
      contributions: ["Guide 업무 기능 개발", "Reference 업무 기능 개발"],
      stack: ["Business application", "Knowledge workflow"],
      decisions: ["세부 설계 판단은 공개 코드가 없어 기재하지 않았습니다."],
      outcome: "업무 사용자가 안내와 참고 정보를 활용하는 기능을 구현했습니다.",
      evidence: "이번 clone 감사 범위 외 저장소로, 공개 이력서의 코드 근거에는 포함하지 않음",
    },
    {
      number: "23",
      label: "디자인 시스템 UI",
      period: "2022.03",
      project: "Carbon Design UI",
      role: "Carbon Design System UI",
      scope: "Carbon Design System · 공통 UI",
      title: "Carbon Design System 기반 UI",
      summary: "Carbon Design System을 적용해 제품의 공통 UI를 개발했습니다.",
      problem: "여러 화면에서 일관된 컴포넌트와 사용자 경험을 제공할 기준이 필요했습니다.",
      contributions: ["Carbon Design System 기반 화면 개발", "공통 UI 구성"],
      stack: ["Carbon Design System", "UI"],
      decisions: ["세부 설계 판단은 공개 코드가 없어 기재하지 않았습니다."],
      outcome: "디자인 시스템을 활용한 일관된 제품 UI 개발 경험을 쌓았습니다.",
      evidence: "이번 clone 감사 범위 외 저장소로, 공개 이력서의 코드 근거에는 포함하지 않음",
    },
  ].map((caseStudy) => ({
    ...caseStudy,
    provenance: caseStudy.evidence.startsWith("코드 감사:") ? "code-observed" : "user-confirmed-only",
  })),
  supporting: [
    "Azure OpenAI 연동과 LLM SDK 마이그레이션",
    "멀티 에이전트 handoff와 온프레미스 운영",
    "금융·제조·헬스케어 데이터 서비스",
  ],
  contact: {
    github: "https://github.com/kimgooneya",
    githubLabel: "github.com/kimgooneya",
    resume: "../resume/developer-resume.html",
  },
};
