export const portfolioData = {
  profile: {
    name: "김수현",
    eyebrow: "B2B AI · DATA SERVICES",
    title: "복잡한 AI\n흐름을 제품으로\n연결합니다",
    summary:
      "Text-to-SQL, 데이터 처리, 인증과 운영 안정화의 코드 경계를 관찰해 정리합니다. 사용자 확인 역할과 clone에서 확인한 동작·검증 근거를 분리해 설명합니다.",
    asOf: "자료 기준일 2026.08",
  },
  capabilities: [
    {
      index: "01",
      title: "AI 실행 흐름",
      detail: "Text-to-SQL DAG, LLM SDK 마이그레이션, 재시도 가능한 작업 단위",
      proof: "질의 계획을 관찰 가능한 단계로 나눕니다.",
    },
    {
      index: "02",
      title: "데이터 신뢰성",
      detail: "입력 정규화, 시계열 변환, 스키마 검증과 오류 경계",
      proof: "입력의 불확실성을 제품 안에서 설명합니다.",
    },
    {
      index: "03",
      title: "제품 운영",
      detail: "인증 쿠키·API 재시도, 런타임 설정, 배포 자동화, 복구 가능한 운영 흐름",
      proof: "기능이 운영되는 마지막 구간까지 설계합니다.",
    },
  ],
  cases: [
    {
      number: "01",
      label: "AI 질의 백엔드",
      period: "2026.07",
      project: "AI 질의 플랫폼",
      role: "백엔드·오케스트레이션 설계 담당",
      scope: "실행 흐름 · 설정 경계 · SQL 오류 대응",
      title: "질의 실행 DAG 전환",
      summary:
        "자연어 질문을 SQL 한 줄이 아닌 계획·실행·검증 단계로 분리하고 실패 지점을 추적할 수 있는 흐름으로 전환",
      problem:
        "질의가 여러 단계의 판단과 조회를 거치며 실패 원인과 재시도 지점을 설명하기 어려운 구조",
      contributions: [
        "Text-to-SQL 처리 흐름을 DAG 구조로 설계하고 핵심 오케스트레이션을 담당",
        "secrets import/export와 Azure 리소스 기반 설정 경계를 정리",
        "로컬 DB 의존성을 줄이고 cloud/keyless 기준으로 실행 환경을 전환",
        "날짜 타입 오류 사전 차단·재시도와 상품 조회 조건·채널 앵커링 로직 개선",
      ],
      stack: ["C#/.NET", "Text-to-SQL", "DAG orchestration", "Azure", "SQL"],
      decisions: [
        "질의 계획을 단계별 책임 단위로 쪼개고 각 결과를 다음 노드의 입력으로 연결",
        "클라우드 자격 증명과 런타임 설정을 코드 밖 경계로 이동",
        "날짜 조건·재시도·실행 결과를 같은 관찰 흐름에서 검증",
      ],
      outcome: "Text-to-SQL 작업에서 확인 가능한 실행 경로와 회귀 기준의 정립",
      evidence: "코드 감사: WorkflowOrchestrationService·Engine.RunAsync·SqlNode의 DAG, fan-in, SELECT guard 경로를 확인",
    },
    {
      number: "02",
      label: "금융 AI 백엔드",
      period: "2026.06",
      project: "금융 AI 서비스",
      role: "AI 백엔드·SDK 마이그레이션 담당",
      scope: "LLM 연동 · 토큰 사용량 · 배포 설정",
      title: "LLM 연동 운영 계약",
      summary: "금융권 AI 서비스의 모델 연동을 SDK와 환경 설정 변화에 흔들리지 않는 구조로 정리",
      problem: "Azure OpenAI 사용량과 SDK 계약 변경 상황에서 설정·토큰·오류 수정이 흩어진 상태",
      contributions: ["Azure OpenAI 토큰 사용량 안정화", "LLM 설정 환경변수화", "Azure.AI.OpenAI SDK v2 마이그레이션", "TCB 오류와 라이브 컨트롤러 기능 반영"],
      stack: ["C#/.NET", "Azure OpenAI", "SDK v2", "환경변수 구성"],
      decisions: ["모델 호출과 환경 설정 분리", "토큰 사용량과 오류 대응을 함께 검증", "기능·최신화 작업을 검증 가능한 변경 단위로 분리"],
      outcome: "SDK 변경과 운영 환경 차이를 분리한 금융 AI 백엔드 업데이트 경로의 단순화",
      evidence: "코드 감사: TCBService·AzureOpenAIService의 typed module, retry, token usage 경계를 확인",
    },
    {
      number: "03",
      label: "인증·실행 플랫폼 runtime",
      period: "2026.03",
      project: "인증·실행 플랫폼 · runtime",
      role: "프론트엔드 빌드·런타임·인증 담당",
      scope: "standalone 빌드 · 환경변수 · 쿠키 정책",
      title: "빌드 산출물·실행 환경 분리",
      summary: "standalone 배포와 Next runtime 환경변수를 정비해 같은 빌드가 환경별로 실행되는 구조로 전환",
      problem: "빌드 시점에 고정된 환경값과 refresh token 쿠키 정책으로 배포 환경마다 오류가 발생하는 구조",
      contributions: ["standalone 빌드 실패 원인 제거", "Next runtime 환경변수 전환", "refresh token 쿠키 정책 조정", "Chrome 실행 경로와 worktree 가이드 정비"],
      stack: ["TypeScript", "Next runtime", "standalone build", "refresh token", "Chrome DevTools"],
      decisions: ["환경값을 빌드 밖 runtime 경계로 이동", "인증 쿠키의 브라우저 동작을 배포 조건과 함께 검증", "반복 작업을 자동화 스크립트와 가이드로 남김"],
      outcome: "배포 환경이 달라도 실행 설정을 재현할 수 있는 프론트엔드 운영 경계의 구축",
      evidence: "코드 감사: auth/token route·axios interceptor·standalone Next config의 실행 경계를 확인",
    },
    {
      number: "04",
      label: "인증·실행 플랫폼 web",
      period: "2026.03",
      project: "인증·실행 플랫폼 · web",
      role: "인증 세션·모델 관리 UI 담당",
      scope: "cross-origin 인증 · 프로바이더 · 채팅 UI",
      title: "인증 경계와 제품 화면 연결",
      summary: "HttpOnly cookie 인증 경계와 모델 관리 화면을 구현해 인증·설정·채팅 선택 흐름을 하나의 제품 경험으로 통합",
      problem: "cross-origin 쿠키, 모델 관리, standalone 설정이 서로 다른 레이어에 흩어진 운영 책임 불명확 상태",
      contributions: ["auth/token route의 HttpOnly cookie 세션 구현", "모델·프로바이더 관리 UI 구현", "채팅 모델 선택 흐름 구현", "Settings·프로필 수정과 standalone 환경변수 정비"],
      stack: ["TypeScript/React", "HttpOnly cookie", "OAuth", "Cosmos DB", "standalone"],
      decisions: ["브라우저 인증 상태를 token route 경계에서 관리", "모델 설정을 화면에서 검증 가능한 상태로 표현", "변경 요청에 재시도·Idempotency-Key 경계를 적용"],
      outcome: "인증에서 모델 선택까지 이어지는 사용자 운영 흐름의 명확화",
      evidence: "코드 감사: auth/token route·api-client의 동시 refresh·401 retry와 문서 삭제·이동 Idempotency-Key를 확인",
    },
    {
      number: "05",
      label: "인증·실행 플랫폼 backend",
      period: "2025.06",
      project: "인증·실행 플랫폼 · backend",
      role: "Keycloak·Identity 모듈 담당",
      scope: "로그인 · Identity · 인증 안정화",
      title: "로그인 흐름 책임 경계 복구",
      summary: "Keycloak 로그인과 Identity 모듈을 구현·리팩터링해 백엔드 인증 흐름을 다시 연결하는 작업",
      problem: "로그인 기능과 Identity 모듈 사이의 책임이 흐려져 인증 변경이 다른 기능까지 흔들릴 수 있는 구조",
      contributions: ["Keycloak 로그인 기능 구현", "Identities 모듈 리팩터링", "Identity 모듈 동작 복구", "백엔드 인증 흐름의 오류 경계 정리"],
      stack: ["C#/.NET", "Keycloak", "Identity", "REST API"],
      decisions: ["로그인과 도메인 Identity 책임 분리", "인증 상태를 백엔드 경계에서 검증", "복구 작업을 작은 변경 단위로 나눠 회귀를 확인"],
      outcome: "인증 변경이 예측 가능한 백엔드 계약 안에서 일어나는 변경 구조의 정리",
      evidence: "코드 감사: KeyCloakService의 authorization/password/refresh 흐름과 EF 기반 model paging을 확인",
    },
    {
      number: "06",
      label: "온프레미스 AI 에이전트",
      period: "2025.12",
      project: "온프레미스 AI 에이전트",
      role: "에이전트 오케스트레이션·운영 UI 담당",
      scope: "handoff · workflow · 운영 대시보드",
      title: "에이전트 간 handoff 운영 흐름",
      summary: "온프레미스 환경에서 여러 에이전트의 handoff와 오케스트레이션을 운영자가 확인할 수 있는 흐름으로 연결",
      problem: "에이전트가 다음 역할로 넘겨지는 과정과 긴급 상태를 한 화면에서 설명하기 어려운 상태",
      contributions: ["AI Agents Phase 4 구현", "agent handoff와 orchestration workflow 연결", "urgent alert·3-panel dashboard 구현", "theme·다국어 회의록 반영"],
      stack: ["AI agents", "orchestration workflow", "on-premise", "3-panel dashboard", "i18n"],
      decisions: ["handoff를 확인 가능한 workflow 단계로 표현", "알림과 회의록을 운영 대시보드 맥락에 배치", "온프레미스 설정과 화면 상태 재현"],
      outcome: "결과·handoff·경고·회의 맥락까지 운영자가 따라갈 수 있는 운영 가시성 확보",
      evidence: "코드 감사: OrchestratorAgent·HandOffWorkflow·ChatHub의 SignalR streaming과 Mongo thread 저장을 확인",
    },
    {
      number: "08",
      label: "금융 문서 PoC",
      period: "2025.08",
      project: "금융 문서 PoC",
      role: "PoC 기능·검증 결과 UI 담당",
      scope: "검증 조건 · 오류 메시지 · 사용자 피드백",
      title: "검증 실패의 다음 행동 안내",
      summary: "금융 문서 처리 PoC의 검증 결과와 오류 메시지를 사용자가 다음 조치를 이해할 수 있는 형태로 개선",
      problem: "검증 실패가 단순 오류 문자열로만 보여 PoC 사용자가 원인과 수정 방향을 판단하기 어려운 구조",
      contributions: ["ChatMessageType 확장", "F1 오류 메시지 표시 개선", "검증 조건과 오차 항목 표시 정비", "테스트 피드백을 화면 흐름에 반영"],
      stack: ["C#/.NET", "document processing", "PoC", "validation UI"],
      decisions: ["오류를 메시지 타입과 화면 상태로 분리", "검증 조건과 결과를 함께 보여줌", "피드백을 재현 가능한 수정 단위로 변환"],
      outcome: "PoC 검증 실패를 숨겨진 예외가 아닌 개선 가능한 피드백으로 전환",
      evidence: "코드 감사: f1 analyzer·ValidationResult와 F2/F3 오류 CSV 재분석, Azure Function 경계를 확인",
    },
    {
      number: "09",
      label: "인증 프론트엔드",
      period: "2025.03",
      project: "React 인증 예제",
      role: "React·Keycloak 인증 프론트엔드 담당",
      scope: "프로젝트 초기화 · 인증 코드 · 사용 문서",
      title: "인증 개념 실행 예제",
      summary: "React 기반 Keycloak 인증 프론트엔드의 초기 구조와 구현 완성 및 사용 문서 정리",
      problem: "인증 예제가 초기 설정과 실제 사용 흐름을 분리해 설명해 팀이 재사용하기 어려운 구조",
      contributions: ["Create React App 기반 구조 초기화", "Keycloak 관련 코드 완성", "인증 사용 문서 정리", "실행 가능한 예제 흐름 구성"],
      stack: ["React", "Keycloak", "Create React App", "JavaScript"],
      decisions: ["실행 진입점과 인증 설정을 분리", "예제 코드와 문서를 같은 변경으로 유지", "재사용 가능한 최소 인증 흐름에 집중"],
      outcome: "팀이 인증 흐름을 직접 실행하고 확장할 수 있는 기준 예제의 구축",
      evidence: "이번 clone 감사 범위 외 저장소로, 공개 이력서의 코드 근거에는 포함하지 않음",
    },
    {
      number: "10",
      label: "문서 파싱 서비스",
      period: "2025.03",
      project: "문서 파싱 API",
      role: "서비스 초기 구조·안정화 담당",
      scope: "엔드포인트 · import 안정성 · API 문서",
      title: "문서 파싱 서비스 초기 경계",
      summary: "문서 파싱 서비스의 기본 구조와 엔드포인트 구성 및 import 안정성과 API 설명 보강",
      problem: "초기 서비스의 구조와 문서가 함께 정리되지 않아 기능 추가 시 진입 비용이 증가하는 상태",
      contributions: ["프로젝트 기본 구조 구성", "문서 엔드포인트 초기화", "import 안정성 개선", "API 주석 보강"],
      stack: ["C#/.NET", "document parsing", "API", "service structure"],
      decisions: ["서비스 진입점과 문서 엔드포인트를 분리", "import 실패를 초기 단계에서 차단", "사용자가 읽을 수 있는 API 계약을 코드와 함께 유지"],
      outcome: "문서 파싱 기능이 확장될 수 있는 기본 서비스 경계의 구축",
      evidence: "이번 clone 감사 범위 외 저장소로, 공개 이력서의 코드 근거에는 포함하지 않음",
    },
    {
      number: "11",
      label: "진단 업무 시스템",
      period: "2024.12",
      project: "진단 rulebase",
      role: "검사 업무 로직·오류 수정 담당",
      scope: "rulebase 오류 · 검사 규칙 · 업무 흐름",
      title: "업무 오류의 도메인 규칙 수정",
      summary: "진단·검사 업무 시스템의 rulebase 입력·검사 업무 로직 수정 및 현장 흐름 안정화",
      problem: "업무 시스템 오류가 화면 한 곳이 아니라 도메인 규칙과 상태 전이에서 발생하는 문제",
      contributions: ["rulebase 입력 오류 재현과 수정", "검사 업무 로직 보완", "회귀 조건을 검증 가능한 변경 단위로 정리", "기능 변경과 운영 오류 대응 병행"],
      stack: ["C#/.NET", "diagnostics", "business rules", "SQL"],
      decisions: ["오류 메시지보다 업무 상태를 먼저 추적", "검사 규칙 변경을 작은 변경 단위로 격리", "수정 결과를 테스트·검증 경계로 남김"],
      outcome: "진단 업무 오류를 재현 가능한 규칙 수정으로 전환",
      evidence: "코드 감사: ExcelFactory의 rulebase 계층 검증·sanitize와 CardRenderer의 go-back 흐름을 확인",
    },
    {
      number: "12",
      label: "AI 상담 모니터링",
      period: "2024.06",
      project: "AI 상담·모니터링 서비스",
      role: "풀스택 대시보드·조회 기능 담당",
      scope: "채팅 이력 · TCB 연동 · 필터 UI",
      title: "운영 데이터 질의 화면",
      summary: "AI 상담·모니터링 서비스의 대시보드·채팅 이력·조회 필터 개선",
      problem: "상담 이력과 운영 상태가 분리되어 담당자가 원인과 추세를 함께 판단하기 어려운 구조",
      contributions: ["채팅 이력 표시 개선", "대시보드 조회 쿼리 개선", "TCB API 연동", "조회 조건·필터 UI와 구조 변경"],
      stack: ["C#/.NET", "dashboard", "TCB API", "query optimization"],
      decisions: ["이력과 상태를 같은 조회 조건으로 연결", "필터를 서버 조회 계약과 맞춤", "장기 운영 개선을 반복 가능한 변경 흐름으로 유지"],
      outcome: "상담 운영자가 이력·상태·필터를 한 흐름에서 비교할 수 있는 운영 흐름",
      evidence: "이번 clone 감사 범위 외 저장소로, 공개 이력서의 코드 근거에는 포함하지 않음",
    },
    {
      number: "13",
      label: "구독·청구 시스템",
      period: "2023.10",
      project: "구독 청구",
      role: "청구·구독 업무 기능 담당",
      scope: "구독 상태 · 청구 흐름 · 오류 수정",
      title: "업무 상태가 이어지는 청구 흐름",
      summary: "구독·청구 업무 시스템의 기능 개발과 오류 수정의 반복 반영",
      problem: "구독 상태와 결제 결과가 어긋나 운영자가 수동으로 원인을 복구해야 하는 상태",
      contributions: ["구독 업무 기능 개발", "청구 흐름 오류 수정", "상태 전이 회귀 대응", "반복 변경을 검증 가능한 단위로 납품"],
      stack: ["C#/.NET", "subscription", "billing", "SQL"],
      decisions: ["청구와 구독 상태를 함께 추적", "오류 수정의 영향 범위를 변경 단위로 분리", "기여 주체가 불명확한 변경은 보수적으로 제외"],
      outcome: "구독과 청구 업무의 상태 변화를 추적 가능한 변경 단위로 관리",
      evidence: "코드 감사: InvoiceService의 subscriptionId 그룹화·reseller 보완과 Cosmos bulk write 경계를 확인",
    },
    {
      number: "14",
      label: "건강 데이터 백엔드",
      period: "2023.09",
      project: "건강 데이터",
      role: "데이터 정규화·통계 기능 담당",
      scope: "누락값 · Journey 통계 · 식이 기능",
      title: "누락 데이터의 업무 규칙화",
      summary: "식이·건강 데이터 서비스의 누락값 정규화·Journey 통계·식이·음료·음주 기능 개선",
      problem: "누락 데이터가 통계와 사용자 기능에서 서로 다르게 해석되어 결과를 신뢰하기 어려운 구조",
      contributions: ["누락값을 0으로 환산하는 처리", "Journey 통계 수정", "식이·음료·음주 기능 반영", "데이터 오류 수정"],
      stack: ["C#/.NET", "Cosmos DB", "health data", "statistics"],
      decisions: ["누락값 정책을 데이터 처리 경계에 고정", "통계 계산과 화면 기능을 같은 규칙으로 검증", "업무 기능과 데이터 수정의 책임을 분리"],
      outcome: "건강 데이터의 빈 값을 통계와 제품 기능에서 일관되게 해석하는 기준",
      evidence: "코드 감사: Mongo checkpoint 증분 조회·단위 정규화·Cosmos glucose 통계 upsert 경계를 확인",
    },
    {
      number: "15",
      label: "주문·업로드 시스템",
      period: "2023.08",
      project: "주문 업로드 서비스",
      role: "업로드 양식·변환 오류 담당",
      scope: "CNPlus 양식 · 파일 변환 · Order 데이터",
      title: "외부 양식의 내부 주문 변환",
      summary: "외부 업로드 양식과 내부 Order 데이터 사이의 변환 오류 개선",
      problem: "외부 양식 변경과 내부 데이터 규칙이 어긋나 주문 업로드가 조용히 실패할 수 있는 구조",
      contributions: ["업로드 템플릿과 CNPlus 변경 양식 지원", "업로드 파일의 Order 변환 오류 수정", "입력 형식과 내부 모델 경계 정비", "반복 업무를 검증 가능한 기능 단위로 분해"],
      stack: ["C#/.NET", "file upload", "Order domain", "data mapping"],
      decisions: ["외부 양식과 내부 모델을 별도 단계로 변환", "변환 실패 지점을 데이터 경계에서 기록", "양식 변경을 기존 주문 로직과 격리"],
      outcome: "외부 파일이 내부 주문으로 바뀌는 경로와 오류 지점을 추적 가능한 변환 경로",
      evidence: "이번 clone 감사 범위 외 저장소로, 공개 이력서의 코드 근거에는 포함하지 않음",
    },
    {
      number: "16",
      label: "문서·지식 AI",
      period: "2023.08",
      project: "문서 지식 기반 AI",
      role: "KnowledgeBase·문서 인식 연동 담당",
      scope: "Factory · DI · Form Recognizer",
      title: "문서 인식 기능 공통 모델 연결",
      summary: "문서·지식 기반 AI 서비스의 KnowledgeBase Factory·DI 구조 구성 및 Azure Form Recognizer 연동",
      problem: "문서 인식 공급자와 도메인 모델이 직접 결합되어 PoC를 제품 기능으로 확장하기 어려운 구조",
      contributions: ["KnowledgeBase Factory 구성", "DI와 NuGet 패키지 구조 정비", "Azure Form Recognizer 연동", "공통 모델·필드·타입 정비"],
      stack: ["C#/.NET", "Azure Form Recognizer", "DI", "NuGet"],
      decisions: ["공급자 구현과 공통 모델을 Factory 경계로 분리", "DI를 통해 교체 가능한 서비스 구성", "문서 필드를 제품 공통 타입으로 정리"],
      outcome: "문서 인식 공급자 변경이 제품 도메인 전체로 번지지 않는 확장 경계의 구축",
      evidence: "이번 clone 감사 범위 외 저장소로, 공개 이력서의 코드 근거에는 포함하지 않음",
    },
    {
      number: "17",
      label: "제조 리포트 웹앱",
      period: "2023.07",
      project: "제조 품질 리포트",
      role: "리포트 웹 애플리케이션 담당",
      scope: "CPVR·APQR · LIMS · 차트·필터",
      title: "제조 데이터 의사결정 리포트",
      summary: "제조 데이터 분석 서비스의 CPVR/APQR 리포트·LIMS 매핑·차트·필터·다운로드·인쇄 기능 개발",
      problem: "제조 리포트가 데이터 조회뿐 아니라 현장 출력과 매핑 오류까지 한 화면에서 견뎌야 하는 구조",
      contributions: ["CPVR/APQR 테이블·차트 구현", "LIMS 매핑과 파라미터 표시", "필터·다운로드·인쇄 기능", "쿼리 오류·빈 값·SQL 방어 로직 개선"],
      stack: ["TypeScript", "React", "Power BI", "LIMS", "SQL"],
      decisions: ["리포트 조회와 출력 흐름을 같은 데이터 계약으로 연결", "빈 값과 쿼리 오류를 화면 상태로 명시", "고객 피드백을 기능 단위 변경으로 분해"],
      outcome: "제조 품질 데이터를 조회·비교·출력하는 업무 흐름의 하나의 웹 리포트 연결",
      evidence: "코드 감사: CPVRReportTable의 그룹화·partial/full 표시와 LIMS mapping·차트·다운로드 경계를 확인",
    },
    {
      number: "18",
      label: "제조 서버리스 로직",
      period: "2023.04",
      project: "제조 서버리스 로직",
      role: "업무 로직·서버리스 백엔드 담당",
      scope: "LIMS CRUD · 캠페인 · 수율 계산",
      title: "리포트 업무 규칙의 서버리스 분리",
      summary: "제조 데이터 도메인의 LIMS 매핑·캠페인·수율 계산 서버리스 기능 구현",
      problem: "리포트 화면이 업무 규칙을 직접 품어 계산과 변경 이력이 관리되기 어려운 구조",
      contributions: ["LIMS 매핑 CRUD", "미부착 판정·대상 조회·변경 이력", "MSP·캠페인·수율 변수 CRUD", "Ad Hoc Calculation 로직"],
      stack: ["C#/.NET", "Azure Functions", "LIMS", "calculation"],
      decisions: ["업무 규칙을 서버리스 함수 경계로 이동", "변경 이력을 데이터 모델에 포함", "수율 계산과 CRUD 책임 분리"],
      outcome: "제조 리포트가 소비할 업무 규칙과 변경 이력을 독립적인 백엔드 흐름으로 구축",
      evidence: "코드 감사: LIMS mapping·MSP/EBR 계산 Azure Function과 CSV 산출 경계를 확인",
    },
    {
      number: "19",
      label: "ASP.NET 인증 예제",
      period: "2023.02",
      project: "Identity 예제",
      role: "ASP.NET Identity 초기 구조 담당",
      scope: "프로젝트 초기화 · Register · scaffolding",
      title: "인증 첫 화면 실행 흐름",
      summary: "ASP.NET Identity 기반 인증 예제의 초기 구조와 회원가입 페이지 scaffolding 구현",
      problem: "인증 예제가 프로젝트 실행 뒤 실제 회원가입 흐름까지 이어져야 학습과 재사용이 가능한 요구",
      contributions: ["ASP.NET Identity 프로젝트 초기화", "Register 페이지 scaffolding", "인증 진입 흐름 구성", "예제 구조 정리"],
      stack: ["ASP.NET", "Identity", "Razor Pages", "C#"],
      decisions: ["기본 인증 모델과 화면 생성을 분리", "Register 흐름을 실제 실행 가능한 예제로 고정", "프레임워크 기본 구조를 확장 가능한 상태로 유지"],
      outcome: "ASP.NET 인증 기능을 처음부터 실행해 볼 수 있는 최소 제품 흐름의 구축",
      evidence: "이번 clone 감사 범위 외 저장소로, 공개 이력서의 코드 근거에는 포함하지 않음",
    },
    {
      number: "20",
      label: "금융 PoC 채팅 UI",
      period: "2022.12",
      project: "금융권 AI PoC",
      role: "채팅 UX·피드백 기능 담당",
      scope: "입력창 · 피드 정렬 · 테스트 피드백",
      title: "PoC 채팅 마찰 개선",
      summary: "금융권 AI PoC의 채팅 입력 UX·피드 정렬·테스트 피드백 요구사항 반영",
      problem: "PoC 사용자가 답변 품질뿐 아니라 입력과 피드백의 매끄러움으로 제품 가능성을 판단하는 기준",
      contributions: ["채팅 입력창 자동 높이 조정", "피드 정렬 개선", "테스트 피드백 요구사항 반영", "사용자 흐름의 작은 회귀 수정"],
      stack: ["React", "chat UI", "UX", "PoC"],
      decisions: ["입력 크기를 콘텐츠에 맞춰 조정", "피드 정렬 규칙을 상태와 함께 검증", "테스트 피드백을 화면 변경으로 구체화"],
      outcome: "금융 AI PoC 채팅 흐름의 입력·응답·피드백 연결",
      evidence: "이번 clone 감사 범위 외 저장소로, 공개 이력서의 코드 근거에는 포함하지 않음",
    },
    {
      number: "21",
      label: "인증·실행 플랫폼 공통 도메인",
      period: "2022.11",
      project: "인증·실행 플랫폼 공통 모델",
      role: "도메인 모델·고객 기능 담당",
      scope: "고객·파트너 CRUD · 공통 타입 · Cosmos",
      title: "플랫폼 공통 기능 모델",
      summary: "공통 도메인 모델·고객·파트너 CRUD·Cosmos bulk service 구현",
      problem: "공통 모델이 기능별로 복제되어 고객·파트너 기능과 데이터 저장 규칙이 빠르게 어긋나는 구조",
      contributions: ["고객·파트너 정보 CRUD", "공통 모델·필드·타입 정비", "Cosmos bulk service 추가", "플랫폼 공통 기능 확장"],
      stack: ["C#/.NET", "Cosmos DB", "domain model", "CRUD"],
      decisions: ["도메인 타입을 기능보다 먼저 공통화", "CRUD와 저장 서비스 책임 분리", "bulk 작업을 별도 서비스 계약으로 구성"],
      outcome: "여러 기능이 같은 도메인 모델과 저장 경계를 공유하는 구조",
      evidence: "이번 clone 감사 범위 외 저장소로, 공개 이력서의 코드 근거에는 포함하지 않음",
    },
    {
      number: "22",
      label: "인증·실행 플랫폼 업무 애플리케이션",
      period: "2021.12",
      project: "인증·실행 플랫폼 업무 기능",
      role: "Guide·Reference 업무 기능 담당",
      scope: "QnA CRUD · Reference CRUD · Storyboard",
      title: "지식 업무 CRUD·화면 흐름 연결",
      summary: "Guide·Reference 업무 기능·CRUD 흐름 구현 및 UI·스토리보드 오류 수정",
      problem: "업무 지식이 CRUD와 화면 탐색에 따로 존재해 사용자가 생성한 정보가 실제 작업 흐름으로 이어지지 않는 구조",
      contributions: ["Guide QnA CRUD", "Reference CRUD", "Guide 화면 버그 수정", "storyboard 기능 개발"],
      stack: ["C#/.NET", "web application", "CRUD", "storyboard"],
      decisions: ["Guide와 Reference를 별도 업무 객체로 모델링", "CRUD 상태와 화면 탐색을 연결", "스토리보드 오류를 기능 변경과 함께 회귀 검증"],
      outcome: "지식 업무가 생성·조회·수정되는 실제 애플리케이션 흐름의 구성",
      evidence: "이번 clone 감사 범위 외 저장소로, 공개 이력서의 코드 근거에는 포함하지 않음",
    },
    {
      number: "23",
      label: "디자인 시스템 UI",
      period: "2022.03",
      project: "Carbon Design UI",
      role: "Carbon Design System UI 담당",
      scope: "Content switcher · 컴포넌트 구현 · 시각 회귀",
      title: "공통 UI 규칙 컴포넌트화",
      summary: "Carbon Design System 기반 UI의 content switcher 컴포넌트 구현",
      problem: "공통 UI가 화면마다 다르게 구현되어 사용성과 유지보수 규칙이 빠르게 분산되는 구조",
      contributions: ["Content switcher 컴포넌트 구현", "Carbon 패턴을 제품 UI에 적용", "컴포넌트 변경을 검증 가능한 단위로 전달"],
      stack: ["Carbon Design System", "React", "component UI"],
      decisions: ["기존 디자인 시스템의 상태 규칙을 우선 적용", "컴포넌트 단위로 재사용 가능한 API 구성", "작은 범위의 변경으로 시각 회귀를 제한"],
      outcome: "제품 화면에서 반복 사용할 수 있는 Carbon 기반 UI 컴포넌트의 구축",
      evidence: "이번 clone 감사 범위 외 저장소로, 공개 이력서의 코드 근거에는 포함하지 않음",
    },
  ],
  supporting: [
    "Azure OpenAI와 SDK v2 전환",
    "에이전트 오케스트레이션과 온프레미스 실행 환경",
    "금융·제조 도메인의 진단, 과금, 사전검증 PoC",
  ],
  contact: {
    github: "https://github.com/kimgooneya",
    githubLabel: "github.com/kimgooneya",
    resume: "../resume/developer-resume.html",
  },
};
