export const portfolioData = {
  profile: {
    name: "김수현",
    eyebrow: "B2B AI · 데이터 서비스 개발자",
    title: "AI·데이터 서비스를\n설계하고 구현합니다",
    summary:
      "Text-to-SQL, 데이터 처리, 인증과 운영 안정화를 중심으로 백엔드와 AI 서비스의 실행 흐름을 설계·구현했습니다. 프로젝트별 역할과 구현 내용, 검증 근거를 구분해 정리했습니다.",
    asOf: "자료 기준일 2026.08",
  },
  capabilities: [
    {
      index: "01",
      title: "AI 실행 흐름",
      detail: "Text-to-SQL DAG, LLM SDK 마이그레이션, 재시도 가능한 작업 단위",
      proof: "질의 계획을 관찰 가능한 실행 단계로 분리합니다.",
    },
    {
      index: "02",
      title: "데이터 신뢰성",
      detail: "입력 정규화, 시계열 변환, 스키마 검증과 오류 경계",
      proof: "입력 오류와 데이터 불확실성을 검증 가능한 규칙으로 정의합니다.",
    },
    {
      index: "03",
      title: "제품 운영",
      detail: "인증 쿠키·API 재시도, 런타임 설정, 배포 자동화, 복구 가능한 운영 흐름",
      proof: "인증·배포·복구까지 포함해 운영 가능한 흐름을 구성합니다.",
    },
  ],
  cases: [
    {
      number: "01",
      label: "AI 질의 백엔드",
      period: "2026.07",
      project: "KT GSI 홈쇼핑",
      role: "사용자 확인 역할 · 백엔드·오케스트레이션",
      scope: "실행 흐름 · 설정 경계 · SQL 오류 대응",
      title: "질의 실행 DAG 전환",
      summary:
        "자연어 질문을 SQL 한 줄이 아닌 계획·실행·검증 단계로 분리하고 실패 지점을 추적할 수 있는 흐름으로 전환",
      problem:
        "질의가 여러 단계의 판단과 조회를 거치며 실패 원인과 재시도 지점을 설명하기 어려운 구조",
      contributions: [
        "코드 감사 관찰: Text-to-SQL 처리 흐름의 DAG 오케스트레이션 경계",
        "코드 감사 관찰: secrets import/export와 Azure 리소스 설정 경계",
        "코드 감사 관찰: cloud/keyless 실행 환경 분리 경계",
        "코드 감사 관찰: 날짜 타입 guard·재시도·상품 조회 채널 앵커링 동작",
      ],
      stack: ["C#/.NET", "Text-to-SQL", "DAG orchestration", "Azure", "SQL"],
      decisions: [
        "질의 계획을 단계별 책임 단위로 쪼개고 각 결과를 다음 노드의 입력으로 연결",
        "클라우드 자격 증명과 런타임 설정을 코드 밖 경계로 이동",
        "날짜 조건·재시도·실행 결과를 같은 관찰 흐름에서 검증",
      ],
      outcome: "Text-to-SQL 작업에서 확인 가능한 실행 경로와 회귀 기준의 정립",
      evidence: "코드 감사: 오케스트레이션 서비스·DAG 실행 엔진·SQL 노드의 DAG, fan-in, SELECT guard 경계를 확인",
    },
    {
      number: "02",
      label: "금융 AI 백엔드",
      period: "2026.06",
      project: "NH농협",
      role: "사용자 확인 역할 · AI 백엔드·SDK 마이그레이션",
      scope: "LLM 연동 · 토큰 사용량 · 배포 설정",
      title: "LLM 연동 운영 계약",
      summary: "금융권 AI 서비스의 모델 연동을 SDK와 환경 설정 변화에 흔들리지 않는 구조로 정리",
      problem: "Azure OpenAI 사용량과 SDK 계약 변경 상황에서 설정·토큰·오류 수정이 흩어진 상태",
      contributions: ["코드 감사 관찰: Azure OpenAI token usage 경계", "코드 감사 관찰: LLM 설정 환경변수 경계", "코드 감사 관찰: Azure OpenAI SDK 호출 경계", "코드 감사 관찰: TCB 오류와 controller 응답 계약"],
      stack: ["C#/.NET", "Azure OpenAI", "SDK v2", "환경변수 구성"],
      decisions: ["모델 호출과 환경 설정 분리", "토큰 사용량과 오류 대응을 함께 검증", "기능·최신화 작업을 검증 가능한 변경 단위로 분리"],
      outcome: "SDK 변경과 운영 환경 차이를 분리한 금융 AI 백엔드 업데이트 경로의 단순화",
      evidence: "코드 감사: TCB 처리·Azure chat client의 typed module, retry, token usage 경계를 확인",
    },
    {
      number: "03",
      label: "인증·실행 플랫폼 runtime",
      period: "2026.03",
      project: "기타",
      role: "사용자 확인 역할 · 프론트엔드 빌드·런타임·인증",
      scope: "standalone 빌드 · 환경변수 · 쿠키 정책",
      title: "빌드 산출물·실행 환경 분리",
      summary: "standalone 배포와 Next runtime 환경변수를 정비해 같은 빌드가 환경별로 실행되는 구조로 전환",
      problem: "빌드 시점에 고정된 환경값과 refresh token 쿠키 정책으로 배포 환경마다 오류가 발생하는 구조",
      contributions: ["코드 감사 관찰: standalone 빌드 산출물 경계", "코드 감사 관찰: Next runtime 환경변수 경계", "코드 감사 관찰: refresh token 쿠키 정책", "코드 감사 관찰: 실행 경로와 runtime 안내 경계"],
      stack: ["TypeScript", "Next runtime", "standalone build", "refresh token", "Chrome DevTools"],
      decisions: ["환경값을 빌드 밖 runtime 경계로 이동", "인증 쿠키의 브라우저 동작을 배포 조건과 함께 검증", "반복 작업을 자동화 스크립트와 가이드로 남김"],
      outcome: "배포 환경이 달라도 실행 설정을 재현할 수 있는 프론트엔드 운영 경계의 구축",
      evidence: "코드 감사: auth/token route·axios interceptor·standalone Next config의 실행 경계를 확인",
    },
    {
      number: "04",
      label: "인증·실행 플랫폼 web",
      period: "2026.03",
      project: "기타",
      role: "사용자 확인 역할 · 인증 세션·모델 관리 UI",
      scope: "cross-origin 인증 · 프로바이더 · 채팅 UI",
      title: "인증 경계와 제품 화면 연결",
      summary: "HttpOnly cookie 인증 경계와 모델 관리 화면을 구현해 인증·설정·채팅 선택 흐름을 하나의 제품 경험으로 통합",
      problem: "cross-origin 쿠키, 모델 관리, standalone 설정이 서로 다른 레이어에 흩어진 운영 책임 불명확 상태",
      contributions: ["코드 감사 관찰: auth/token route의 HttpOnly cookie 세션", "코드 감사 관찰: 모델·프로바이더 관리 UI 경계", "코드 감사 관찰: 채팅 모델 선택 흐름", "코드 감사 관찰: Settings·프로필·standalone 환경변수 경계"],
      stack: ["TypeScript/React", "HttpOnly cookie", "OAuth", "Cosmos DB", "standalone"],
      decisions: ["브라우저 인증 상태를 token route 경계에서 관리", "모델 설정을 화면에서 검증 가능한 상태로 표현", "변경 요청에 재시도·Idempotency-Key 경계를 적용"],
      outcome: "인증에서 모델 선택까지 이어지는 사용자 운영 흐름의 명확화",
      evidence: "코드 감사: auth/token route·api-client의 동시 refresh·401 retry와 문서 삭제·이동 Idempotency-Key를 확인",
    },
    {
      number: "05",
      label: "인증·실행 플랫폼 backend",
      period: "2025.06",
      project: "기타",
      role: "사용자 확인 역할 · Keycloak·Identity 모듈",
      scope: "로그인 · Identity · 인증 안정화",
      title: "로그인 흐름 책임 경계 복구",
      summary: "Keycloak 로그인과 Identity 모듈을 구현·리팩터링해 백엔드 인증 흐름을 다시 연결하는 작업",
      problem: "로그인 기능과 Identity 모듈 사이의 책임이 흐려져 인증 변경이 다른 기능까지 흔들릴 수 있는 구조",
      contributions: ["코드 감사 관찰: Keycloak 로그인 흐름", "코드 감사 관찰: Identities 모듈 경계", "코드 감사 관찰: Identity 모듈 동작 경로", "코드 감사 관찰: 백엔드 인증 오류 경계"],
      stack: ["C#/.NET", "Keycloak", "Identity", "REST API"],
      decisions: ["로그인과 도메인 Identity 책임 분리", "인증 상태를 백엔드 경계에서 검증", "복구 작업을 작은 변경 단위로 나눠 회귀를 확인"],
      outcome: "인증 변경이 예측 가능한 백엔드 계약 안에서 일어나는 변경 구조의 정리",
      evidence: "코드 감사: KeyCloakService의 authorization/password/refresh 흐름과 EF 기반 model paging을 확인",
    },
    {
      number: "06",
      label: "온프레미스 AI 에이전트",
      period: "2025.12",
      project: "두바이 GDRFA",
      role: "사용자 확인 역할 · 에이전트 오케스트레이션·운영 UI",
      scope: "handoff · workflow · 운영 대시보드",
      title: "에이전트 간 handoff 운영 흐름",
      summary: "온프레미스 환경에서 여러 에이전트의 handoff와 오케스트레이션을 운영자가 확인할 수 있는 흐름으로 연결",
      problem: "에이전트가 다음 역할로 넘겨지는 과정과 긴급 상태를 한 화면에서 설명하기 어려운 상태",
      contributions: ["코드 감사 관찰: agent handoff와 orchestration workflow", "코드 감사 관찰: SignalR streaming과 thread 저장", "코드 감사 관찰: 운영 alert·dashboard 경계", "코드 감사 관찰: theme·다국어 UI 경계"],
      stack: ["AI agents", "orchestration workflow", "on-premise", "3-panel dashboard", "i18n"],
      decisions: ["handoff를 확인 가능한 workflow 단계로 표현", "알림과 회의록을 운영 대시보드 맥락에 배치", "온프레미스 설정과 화면 상태 재현"],
      outcome: "결과·handoff·경고·회의 맥락까지 운영자가 따라갈 수 있는 운영 가시성 확보",
      evidence: "코드 감사: 오케스트레이터·handoff workflow·채팅 허브의 SignalR streaming과 Mongo thread 저장을 확인",
    },
    {
      number: "08",
      label: "금융 문서 PoC",
      period: "2025.08",
      project: "NH농협",
      role: "사용자 확인 역할 · PoC 기능·검증 결과 UI",
      scope: "검증 조건 · 오류 메시지 · 사용자 피드백",
      title: "검증 실패의 다음 행동 안내",
      summary: "금융 문서 처리 PoC의 검증 결과와 오류 메시지를 사용자가 다음 조치를 이해할 수 있는 형태로 개선",
      problem: "검증 실패가 단순 오류 문자열로만 보여 PoC 사용자가 원인과 수정 방향을 판단하기 어려운 구조",
      contributions: ["코드 감사 관찰: validation 결과 메시지 타입 경계", "코드 감사 관찰: feature 오류 결과 표시 경계", "코드 감사 관찰: 검증 조건·오류 항목 결과 계약", "코드 감사 관찰: CSV 재분석과 화면 결과 흐름"],
      stack: ["C#/.NET", "document processing", "PoC", "validation UI"],
      decisions: ["오류를 메시지 타입과 화면 상태로 분리", "검증 조건과 결과를 함께 보여줌", "피드백을 재현 가능한 수정 단위로 변환"],
      outcome: "PoC 검증 실패를 숨겨진 예외가 아닌 개선 가능한 피드백으로 전환",
      evidence: "코드 감사: 분석 서비스·ValidationResult와 후속 오류 CSV 재분석, Azure Function 경계를 확인",
    },
    {
      number: "09",
      label: "인증 프론트엔드",
      period: "2025.03",
      project: "기타",
      role: "사용자 확인만 · React·Keycloak 인증 프론트엔드",
      scope: "공개 clone 감사 제외",
      title: "사용자 확인 이력 · 인증 예제",
      summary: "공개 clone 감사 제외 · 사용자 확인 이력에만 한정",
      problem: "공개 clone 감사 제외 · 문제 정의는 사용자 확인 이력에 한정",
      contributions: ["공개 clone 감사 제외 · 세부 기여는 사용자 확인 이력에 한정"],
      stack: ["공개 코드 근거 없음"],
      decisions: ["공개 clone 감사 제외 · 설계 판단은 확인하지 않음"],
      outcome: "공개 clone 감사 제외 · 결과는 사용자 확인 이력으로만 보관",
      evidence: "이번 clone 감사 범위 외 저장소로, 공개 이력서의 코드 근거에는 포함하지 않음",
    },
    {
      number: "10",
      label: "문서 파싱 서비스",
      period: "2025.03",
      project: "기타",
      role: "사용자 확인만 · 서비스 초기 구조·안정화",
      scope: "공개 clone 감사 제외",
      title: "사용자 확인 이력 · 문서 파싱",
      summary: "공개 clone 감사 제외 · 사용자 확인 이력에만 한정",
      problem: "공개 clone 감사 제외 · 문제 정의는 사용자 확인 이력에 한정",
      contributions: ["공개 clone 감사 제외 · 세부 기여는 사용자 확인 이력에 한정"],
      stack: ["공개 코드 근거 없음"],
      decisions: ["공개 clone 감사 제외 · 설계 판단은 확인하지 않음"],
      outcome: "공개 clone 감사 제외 · 결과는 사용자 확인 이력으로만 보관",
      evidence: "이번 clone 감사 범위 외 저장소로, 공개 이력서의 코드 근거에는 포함하지 않음",
    },
    {
      number: "11",
      label: "진단 업무 시스템",
      period: "2024.12",
      project: "기타",
      role: "사용자 확인 역할 · 검사 업무 로직·오류 수정",
      scope: "rulebase 오류 · 검사 규칙 · 업무 흐름",
      title: "업무 오류의 도메인 규칙 수정",
      summary: "진단·검사 업무 시스템의 rulebase 입력·검사 업무 로직 수정 및 현장 흐름 안정화",
      problem: "업무 시스템 오류가 화면 한 곳이 아니라 도메인 규칙과 상태 전이에서 발생하는 문제",
      contributions: ["코드 감사 관찰: rulebase 입력 검증·sanitize", "코드 감사 관찰: 검사 업무 상태 전이", "코드 감사 관찰: 회귀 조건을 검증하는 경계", "코드 감사 관찰: 카드 UI와 go-back 흐름"],
      stack: ["C#/.NET", "diagnostics", "business rules", "SQL"],
      decisions: ["오류 메시지보다 업무 상태를 먼저 추적", "검사 규칙 변경을 작은 변경 단위로 격리", "수정 결과를 테스트·검증 경계로 남김"],
      outcome: "진단 업무 오류를 재현 가능한 규칙 수정으로 전환",
      evidence: "코드 감사: Excel ingestion의 rulebase 계층 검증·sanitize와 카드 UI의 go-back 흐름을 확인",
    },
    {
      number: "12",
      label: "AI 상담 모니터링",
      period: "2024.06",
      project: "교보생명",
      role: "사용자 확인만 · 풀스택 대시보드·조회 기능",
      scope: "공개 clone 감사 제외",
      title: "사용자 확인 이력 · 운영 화면",
      summary: "공개 clone 감사 제외 · 사용자 확인 이력에만 한정",
      problem: "공개 clone 감사 제외 · 문제 정의는 사용자 확인 이력에 한정",
      contributions: ["공개 clone 감사 제외 · 세부 기여는 사용자 확인 이력에 한정"],
      stack: ["공개 코드 근거 없음"],
      decisions: ["공개 clone 감사 제외 · 설계 판단은 확인하지 않음"],
      outcome: "공개 clone 감사 제외 · 결과는 사용자 확인 이력으로만 보관",
      evidence: "이번 clone 감사 범위 외 저장소로, 공개 이력서의 코드 근거에는 포함하지 않음",
    },
    {
      number: "13",
      label: "구독·청구 시스템",
      period: "2023.10",
      project: "SPin · Azure 구독청구 시스템",
      role: "사용자 확인 역할 · 청구·구독 업무 기능",
      scope: "구독 상태 · 청구 흐름 · 오류 수정",
      title: "업무 상태가 이어지는 청구 흐름",
      summary: "구독·청구 업무 시스템의 기능 개발과 오류 수정의 반복 반영",
      problem: "구독 상태와 결제 결과가 어긋나 운영자가 수동으로 원인을 복구해야 하는 상태",
      contributions: ["코드 감사 관찰: subscriptionId별 주문 라인 집계", "코드 감사 관찰: 청구 reset·오류 경계", "코드 감사 관찰: 상태 전이와 repository 경계", "코드 감사 관찰: Cosmos bulk write 경계"],
      stack: ["C#/.NET", "subscription", "billing", "SQL"],
      decisions: ["청구와 구독 상태를 함께 추적", "오류 수정의 영향 범위를 변경 단위로 분리", "기여 주체가 불명확한 변경은 보수적으로 제외"],
      outcome: "구독과 청구 업무의 상태 변화를 추적 가능한 변경 단위로 관리",
      evidence: "코드 감사: 청구 서비스의 subscriptionId 그룹화·reseller 보완과 Cosmos bulk write 경계를 확인",
    },
    {
      number: "14",
      label: "건강 데이터 백엔드",
      period: "2023.09",
      project: "KB헬스케어 · 기관명 확인 필요",
      role: "사용자 확인 역할 · 데이터 정규화·통계 기능",
      scope: "누락값 · Journey 통계 · 식이 기능",
      title: "누락 데이터의 업무 규칙화",
      summary: "식이·건강 데이터 서비스의 누락값 정규화·Journey 통계·식이·음료·음주 기능 개선",
      problem: "누락 데이터가 통계와 사용자 기능에서 서로 다르게 해석되어 결과를 신뢰하기 어려운 구조",
      contributions: ["코드 감사 관찰: 누락값 기본값과 통계 집계 경계", "코드 감사 관찰: checkpoint 기반 기간 통계", "코드 감사 관찰: 단위 정규화와 source/date 집계", "코드 감사 관찰: 데이터 결함과 테스트 한계"],
      stack: ["C#/.NET", "Cosmos DB", "health data", "statistics"],
      decisions: ["누락값 정책을 데이터 처리 경계에 고정", "통계 계산과 화면 기능을 같은 규칙으로 검증", "업무 기능과 데이터 수정의 책임을 분리"],
      outcome: "건강 데이터의 빈 값을 통계와 제품 기능에서 일관되게 해석하는 기준",
      evidence: "코드 감사: Mongo checkpoint 증분 조회·단위 정규화·Cosmos glucose 통계 upsert 경계를 확인",
    },
    {
      number: "15",
      label: "주문·업로드 시스템",
      period: "2023.08",
      project: "주문 업로드 서비스",
      role: "사용자 확인만 · 업로드 양식·변환 오류",
      scope: "공개 clone 감사 제외",
      title: "사용자 확인 이력 · 주문 변환",
      summary: "공개 clone 감사 제외 · 사용자 확인 이력에만 한정",
      problem: "공개 clone 감사 제외 · 문제 정의는 사용자 확인 이력에 한정",
      contributions: ["공개 clone 감사 제외 · 세부 기여는 사용자 확인 이력에 한정"],
      stack: ["공개 코드 근거 없음"],
      decisions: ["공개 clone 감사 제외 · 설계 판단은 확인하지 않음"],
      outcome: "공개 clone 감사 제외 · 결과는 사용자 확인 이력으로만 보관",
      evidence: "이번 clone 감사 범위 외 저장소로, 공개 이력서의 코드 근거에는 포함하지 않음",
    },
    {
      number: "16",
      label: "문서·지식 AI",
      period: "2023.08",
      project: "문서 지식 기반 AI",
      role: "사용자 확인만 · KnowledgeBase·문서 인식 연동",
      scope: "공개 clone 감사 제외",
      title: "사용자 확인 이력 · 문서 인식",
      summary: "공개 clone 감사 제외 · 사용자 확인 이력에만 한정",
      problem: "공개 clone 감사 제외 · 문제 정의는 사용자 확인 이력에 한정",
      contributions: ["공개 clone 감사 제외 · 세부 기여는 사용자 확인 이력에 한정"],
      stack: ["공개 코드 근거 없음"],
      decisions: ["공개 clone 감사 제외 · 설계 판단은 확인하지 않음"],
      outcome: "공개 clone 감사 제외 · 결과는 사용자 확인 이력으로만 보관",
      evidence: "이번 clone 감사 범위 외 저장소로, 공개 이력서의 코드 근거에는 포함하지 않음",
    },
    {
      number: "17",
      label: "제조 리포트 웹앱",
      period: "2023.07",
      project: "제조 품질 시스템",
      role: "사용자 확인 역할 · 리포트 웹 애플리케이션",
      scope: "CPVR·APQR · LIMS · 차트·필터",
      title: "제조 데이터 의사결정 리포트",
      summary: "제조 데이터 분석 서비스의 CPVR/APQR 리포트·LIMS 매핑·차트·필터·다운로드·인쇄 기능 개발",
      problem: "제조 리포트가 데이터 조회뿐 아니라 현장 출력과 매핑 오류까지 한 화면에서 견뎌야 하는 구조",
      contributions: ["코드 감사 관찰: report grouping·partial/full 표시", "코드 감사 관찰: LIMS mapping과 parameter 표시", "코드 감사 관찰: filter·download·print 경계", "코드 감사 관찰: query 오류·빈 값·SQL 방어 경계"],
      stack: ["TypeScript", "React", "Power BI", "LIMS", "SQL"],
      decisions: ["리포트 조회와 출력 흐름을 같은 데이터 계약으로 연결", "빈 값과 쿼리 오류를 화면 상태로 명시", "고객 피드백을 기능 단위 변경으로 분해"],
      outcome: "제조 품질 데이터를 조회·비교·출력하는 업무 흐름의 하나의 웹 리포트 연결",
      evidence: "코드 감사: 리포트 테이블의 그룹화·partial/full 표시와 LIMS mapping·차트·다운로드 경계를 확인",
    },
    {
      number: "18",
      label: "제조 서버리스 로직",
      period: "2023.04",
      project: "제조 품질 시스템",
      role: "사용자 확인 역할 · 업무 로직·서버리스 백엔드",
      scope: "LIMS CRUD · 캠페인 · 수율 계산",
      title: "리포트 업무 규칙의 서버리스 분리",
      summary: "제조 데이터 도메인의 LIMS 매핑·캠페인·수율 계산 서버리스 기능 구현",
      problem: "리포트 화면이 업무 규칙을 직접 품어 계산과 변경 이력이 관리되기 어려운 구조",
      contributions: ["코드 감사 관찰: LIMS mapping CRUD 경계", "코드 감사 관찰: 대상 조회·변경 상태 계산", "코드 감사 관찰: MSP·campaign·수율 변수 경계", "코드 감사 관찰: Blob Excel calculation 결과 경계"],
      stack: ["C#/.NET", "Azure Functions", "LIMS", "calculation"],
      decisions: ["업무 규칙을 서버리스 함수 경계로 이동", "변경 이력을 데이터 모델에 포함", "수율 계산과 CRUD 책임 분리"],
      outcome: "제조 리포트가 소비할 업무 규칙과 변경 이력을 독립적인 백엔드 흐름으로 구축",
      evidence: "코드 감사: LIMS mapping·MSP/EBR 계산 Azure Function과 CSV 산출 경계를 확인",
    },
    {
      number: "19",
      label: "ASP.NET 인증 예제",
      period: "2023.02",
      project: "Identity 예제",
      role: "사용자 확인만 · ASP.NET Identity 초기 구조",
      scope: "공개 clone 감사 제외",
      title: "사용자 확인 이력 · 인증 예제",
      summary: "공개 clone 감사 제외 · 사용자 확인 이력에만 한정",
      problem: "공개 clone 감사 제외 · 문제 정의는 사용자 확인 이력에 한정",
      contributions: ["공개 clone 감사 제외 · 세부 기여는 사용자 확인 이력에 한정"],
      stack: ["공개 코드 근거 없음"],
      decisions: ["공개 clone 감사 제외 · 설계 판단은 확인하지 않음"],
      outcome: "공개 clone 감사 제외 · 결과는 사용자 확인 이력으로만 보관",
      evidence: "이번 clone 감사 범위 외 저장소로, 공개 이력서의 코드 근거에는 포함하지 않음",
    },
    {
      number: "20",
      label: "금융 PoC 채팅 UI",
      period: "2022.12",
      project: "금융권 AI PoC",
      role: "사용자 확인만 · 채팅 UX·피드백 기능",
      scope: "공개 clone 감사 제외",
      title: "사용자 확인 이력 · 채팅 UI",
      summary: "공개 clone 감사 제외 · 사용자 확인 이력에만 한정",
      problem: "공개 clone 감사 제외 · 문제 정의는 사용자 확인 이력에 한정",
      contributions: ["공개 clone 감사 제외 · 세부 기여는 사용자 확인 이력에 한정"],
      stack: ["공개 코드 근거 없음"],
      decisions: ["공개 clone 감사 제외 · 설계 판단은 확인하지 않음"],
      outcome: "공개 clone 감사 제외 · 결과는 사용자 확인 이력으로만 보관",
      evidence: "이번 clone 감사 범위 외 저장소로, 공개 이력서의 코드 근거에는 포함하지 않음",
    },
    {
      number: "21",
      label: "인증·실행 플랫폼 공통 도메인",
      period: "2022.11",
      project: "기타",
      role: "사용자 확인만 · 도메인 모델·고객 기능",
      scope: "공개 clone 감사 제외",
      title: "사용자 확인 이력 · 공통 모델",
      summary: "공개 clone 감사 제외 · 사용자 확인 이력에만 한정",
      problem: "공개 clone 감사 제외 · 문제 정의는 사용자 확인 이력에 한정",
      contributions: ["공개 clone 감사 제외 · 세부 기여는 사용자 확인 이력에 한정"],
      stack: ["공개 코드 근거 없음"],
      decisions: ["공개 clone 감사 제외 · 설계 판단은 확인하지 않음"],
      outcome: "공개 clone 감사 제외 · 결과는 사용자 확인 이력으로만 보관",
      evidence: "이번 clone 감사 범위 외 저장소로, 공개 이력서의 코드 근거에는 포함하지 않음",
    },
    {
      number: "22",
      label: "인증·실행 플랫폼 업무 애플리케이션",
      period: "2021.12",
      project: "기타",
      role: "사용자 확인만 · Guide·Reference 업무 기능",
      scope: "공개 clone 감사 제외",
      title: "사용자 확인 이력 · 지식 업무",
      summary: "공개 clone 감사 제외 · 사용자 확인 이력에만 한정",
      problem: "공개 clone 감사 제외 · 문제 정의는 사용자 확인 이력에 한정",
      contributions: ["공개 clone 감사 제외 · 세부 기여는 사용자 확인 이력에 한정"],
      stack: ["공개 코드 근거 없음"],
      decisions: ["공개 clone 감사 제외 · 설계 판단은 확인하지 않음"],
      outcome: "공개 clone 감사 제외 · 결과는 사용자 확인 이력으로만 보관",
      evidence: "이번 clone 감사 범위 외 저장소로, 공개 이력서의 코드 근거에는 포함하지 않음",
    },
    {
      number: "23",
      label: "디자인 시스템 UI",
      period: "2022.03",
      project: "Carbon Design UI",
      role: "사용자 확인만 · Carbon Design System UI",
      scope: "공개 clone 감사 제외",
      title: "사용자 확인 이력 · 공통 UI",
      summary: "공개 clone 감사 제외 · 사용자 확인 이력에만 한정",
      problem: "공개 clone 감사 제외 · 문제 정의는 사용자 확인 이력에 한정",
      contributions: ["공개 clone 감사 제외 · 세부 기여는 사용자 확인 이력에 한정"],
      stack: ["공개 코드 근거 없음"],
      decisions: ["공개 clone 감사 제외 · 설계 판단은 확인하지 않음"],
      outcome: "공개 clone 감사 제외 · 결과는 사용자 확인 이력으로만 보관",
      evidence: "이번 clone 감사 범위 외 저장소로, 공개 이력서의 코드 근거에는 포함하지 않음",
    },
  ].map((caseStudy) => ({
    ...caseStudy,
    provenance: caseStudy.evidence.startsWith("코드 감사:") ? "code-observed" : "user-confirmed-only",
  })),
  supporting: [
    "Azure OpenAI와 SDK v2 전환",
    "에이전트 오케스트레이션과 온프레미스 실행 환경",
    "금융·제조 도메인의 진단, 과금, 사전검증 PoC",
  ],
  contact: {
    github: "https://github.com/kimgooneya",
    githubLabel: "github.com/kimgooneya",
    resume: "../resume/developer-resume.html",
  },
};
